// Generated by Wrangler by running `wrangler types`

interface Env {
	VERTEX_REGION: "us-east5";
	DEEPGRAM_TRAFFIC_PCT: "20";
	WHISPER_TRAFFIC_PCT: "0";
	PARAKEET_TRAFFIC_PCT: "80";
	DUAL_SEND_PCT: "0";
	PARAKEET_URL: "https://audio.screenpi.pe";
	WHISPER_URL: "";
	SELF_HOSTED_TRANSCRIPTION_URL: "https://audio.screenpi.pe";
	RATE_LIMITER: DurableObjectNamespace<import("./src/index").RateLimiter>;
	DB: D1Database;
}
