/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options passed to `new Recorder({...})` from JS. */
export interface RecorderOptions {
  /** Absolute path where the MP4 will be written. */
  output: string
  /**
   * Single-monitor MP4 fallback. When `mp4Monitors` is also provided,
   * it takes precedence and this field is ignored.
   *
   * - `Some(id)` — record only this monitor to MP4 at `output`
   *   (legacy behavior, kept for backward compat).
   * - `None` + no `mp4Monitors` → record **every attached monitor**
   *   (the new default — see `mp4Monitors` for the per-monitor file
   *   path expansion).
   */
  monitorId?: number
  /**
   * Which monitors to record to MP4. Mirrors `pairedMonitors` for the
   * video pipeline:
   *
   * - `undefined` (default) — record every attached monitor, one MP4
   *   per display.
   * - `[id, id, ...]` — pin MP4 to exactly these IDs.
   * - `[]` — disable MP4 entirely while still letting paired capture
   *   run (no ffmpeg process is started).
   *
   * When more than one monitor is recorded, `output` is treated as a
   * path template. If it contains the literal substring
   * `{monitor_id}`, that's substituted per monitor. Otherwise the
   * recorder auto-suffixes `-monitor-{id}` before the file extension.
   */
  mp4Monitors?: Array<number>
  /** Reserved for future MP4 audio muxing. Accepted today but not recorded. */
  microphone?: boolean
  /** Reserved for future system-audio muxing. Accepted today but not recorded. */
  systemAudio?: boolean
  /**
   * Substring patterns matched against the focused app name and window title
   * (case-insensitive). While a matching window is in focus, the recorder
   * skips writing frames — the MP4 contains a hard cut over the filtered
   * period.
   *
   * Each pattern may use an optional `App::Title` scope: `"Slack::#hr"`
   * skips only the #hr window inside Slack and leaves other Slack channels
   * recording. `"::Confidential"` matches any app whose title contains
   * "Confidential". Plain `"Slack"` keeps the legacy "app OR title
   * contains" behavior.
   */
  ignoredWindows?: Array<string>
  /**
   * Substring whitelist. If non-empty, frames are written ONLY while the
   * focused app name or window title matches at least one pattern.
   *
   * Scoped entries (`"Greenhouse::Candidates"`) create a per-app whitelist
   * — other apps stay unaffected, so this whitelists only that window
   * without inadvertently blocking Slack/Chrome. Unscoped entries keep
   * the legacy "must match app or title" global semantics.
   */
  includedWindows?: Array<string>
  /**
   * URL patterns to skip (case-insensitive, domain-aware matching).
   * When the focused window is a browser navigated to a matching URL,
   * the recorder skips writing frames.
   */
  ignoredUrls?: Array<string>
  /**
   * When set, the recorder runs the engine's event-driven paired-capture
   * pipeline in parallel with the MP4 writer: typed UI events (click,
   * typing pause, app switch, etc.) + visual-change detection + idle
   * baseline fire `paired_capture()` against a SQLite at
   * `{dataDir}/db.sqlite`. JPEG snapshots are written under
   * `{dataDir}/data/`. Same DB schema and trigger taxonomy the
   * screenpipe CLI writes.
   */
  dataDir?: string
  /**
   * Which monitors to record paired captures from. Only meaningful when
   * `dataDir` is set.
   */
  pairedMonitors?: Array<number>
  /**
   * Per-event-type toggles for the platform UI hooks that feed
   * paired-capture triggers. When `undefined`, uses the SDK's defaults
   * (clicks, typing pauses, app switches, clipboard ON; keystrokes,
   * scroll, mouse-move, window-focus OFF).
   */
  uiCapture?: UiCaptureOptions
}
/**
 * Per-event-type toggles passed through to the platform UI hooks. Each
 * field defaults to the SDK's default when left undefined, so callers
 * can override one knob without restating the others.
 */
export interface UiCaptureOptions {
  /**
   * Capture mouse clicks. Default: true.
   * Drives the `click` capture trigger.
   */
  captureClicks?: boolean
  /**
   * Capture aggregated text input (typing-pause bursts). Default: true.
   * Drives the `typing_pause` capture trigger.
   */
  captureText?: boolean
  /**
   * Capture individual keystrokes. Default: false.
   * HIGH PRIVACY RISK — individual key events stream through the hook.
   */
  captureKeystrokes?: boolean
  /** Capture app-switch events. Default: true. */
  captureAppSwitch?: boolean
  /** Capture window-focus changes within the same app. Default: false. */
  captureWindowFocus?: boolean
  /**
   * Capture scroll events. Default: false.
   * Required to enable the `scroll_stop` capture trigger.
   */
  captureScroll?: boolean
  /** Capture clipboard operations. Default: true. */
  captureClipboard?: boolean
  /**
   * Include clipboard content in the event payload. Default: true.
   * PRIVACY RISK — clipboard text may include passwords/tokens.
   */
  captureClipboardContent?: boolean
  /** Resolve accessibility-element context on each click. Default: true. */
  captureContext?: boolean
  /** Capture mouse-move events. Default: false. */
  captureMouseMove?: boolean
}
/** Permission status returned by `requestPermissions`. */
export interface PermissionStatus {
  screen: boolean
  microphone: boolean
}
/** Lightweight snapshot of the user's focused window. */
export interface FocusedApp {
  appName: string
  windowTitle: string
  browserUrl?: string
  nodeCount: number
  walkMs: number
}
/** Current state of the window/URL filter. */
export interface FilterStatus {
  paused: boolean
  reason?: string
}
/**
 * Patch passed to `Recorder.setFilters({...})` for live filter updates.
 * Any field omitted (or sent as `null`) clears that list. All three fields
 * follow the same matching semantics as the matching `RecorderOptions`
 * fields — including the `App::Title` scope convention on
 * `ignored_windows` / `included_windows`.
 */
export interface FilterPatch {
  ignoredWindows?: Array<string>
  includedWindows?: Array<string>
  ignoredUrls?: Array<string>
}
/**
 * Prompt the OS for screen recording + microphone permissions if not already
 * granted. On macOS this triggers the TCC dialog the first time; on
 * subsequent calls it just reports current state.
 */
export declare function requestPermissions(): Promise<PermissionStatus>
/**
 * Record a user's screen to an MP4 file.
 *
 * ```ts
 * import { Recorder } from '@screenpipe/sdk';
 *
 * const r = new Recorder({ output: '/tmp/session.mp4' });
 * await r.start();
 * // ... user does stuff ...
 * await r.stop();
 * ```
 */
export declare class Recorder {
  /** Construct a recorder. Does NOT start capture — call `.start()`. */
  constructor(options: RecorderOptions)
  /**
   * Begin writing frames to the output file. Resolves once the
   * capture stream is live and the MP4 header has been written.
   */
  start(): Promise<void>
  /**
   * Stop capture. Flushes the MP4 trailer and closes the file.
   * Idempotent (safe to call twice).
   */
  stop(): Promise<void>
  /**
   * Capture a single frame of the recorder's monitor as a JPEG buffer.
   * Works whether or not `start()` has been called.
   */
  snapshot(): Promise<Buffer>
  /**
   * Number of frames written to the MP4 since `start()`. Returns 0
   * if not recording.
   */
  framesWritten(): Promise<number>
  /**
   * Current microphone input level in [0, 1] (smoothed linear RMS).
   * The first call starts a persistent capture on the default input
   * device and triggers the macOS Microphone TCC prompt if not yet
   * granted. Independent of `start()`.
   */
  audioLevel(): Promise<number>
  /** Current state of the window/URL filter. */
  filterStatus(): Promise<FilterStatus>
  /** Replace the active filter lists at runtime. */
  setFilters(patch: FilterPatch): Promise<void>
  /**
   * Snapshot of the currently focused window via accessibility APIs.
   * Returns `null` when no focused window is detected or the window
   * is on the skip-list.
   *
   * macOS: requires Accessibility permission.
   */
  focusedApp(): Promise<FocusedApp | null>
}
